- name: create ec2 and r53
  hosts: localhost
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0a57c1e73eeeeb737
    zone_id: "Z07458192RR2CQRCYPMGD"
    domain_name: "harshithdaws86s.fun"
    ansible_python_interpreter: /usr/bin/python3
    # Define instances here or pass via -e
    instances:
      - frontend
      - mongodb
      - redis
      - mysql
      - rabbitmq

  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        wait: yes
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output

    - name: create route53 record for private IPs
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}.{{ domain_name }}"
        type: A
        ttl: 60
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite: true
      loop: "{{ ec2_output.results }}"

    - name: create route53 record for frontend public IP
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ domain_name }}"
        type: A
        ttl: 60
        value: "{{ item.instances[0].public_ip_address }}"
        overwrite: true
      when: item.item == "frontend"
      loop: "{{ ec2_output.results }}"
